// app/layout.tsx
import type { Metadata } from "next";
import { Inter,Nunito } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose what you need
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Tobams Group App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${nunito.className} min-h-screen flex flex-col`}>
        <Nav />
        <main className="flex-grow">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}